import { IonContent,IonPage } from "@ionic/react"
import Header from "./Header"

export default function PrivacyPolicy(){
    return (
        <>
        <IonPage>
          <Header/>
          <IonContent>
        <div style={{margin:"1rem"}}>
<p><strong>Effective Date: 21-11-2021</strong></p>
<h3>Your privacy is important to us</h3>
<p>It is ThePetalGlow's policy to respect your privacy regarding any information we may collect while operating our website. This Privacy Policy applies to <a href="https://thepetalglow.com"> thepetalglow.com</a> (hereinafter, "us", "we", or "thepetalglow.com"). We respect your privacy and are committed to protecting personally identifiable information you may provide us through the Website. We have adopted this privacy policy ("Privacy Policy") to explain what information may be collected on our Website, how we use this information, and under what circumstances we may disclose the information to third parties. This Privacy Policy applies only to information we collect through the Website and does not apply to our collection of information from other sources.</p>
<p>This Privacy Policy, together with the Terms of service posted on our Website, set forth the general rules and policies governing your use of our Website. Depending on your activities when visiting our Website, you may be required to agree to additional terms of service.</p><h1 class="text-center">Privacy Policy</h1>

<h2 id="websitevisitors">1. Website Visitors</h2><p>Like most website operators, ThePetalGlow collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. ThePetalGlow's purpose in collecting non-personally identifying information is to better understand how ThePetalGlow's visitors use its website. From time to time, ThePetalGlow may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website.</p>
<p>ThePetalGlow also collects potentially personally-identifying information like Internet Protocol (IP) addresses for logged in users and for users leaving comments on https://thepetalglow.com blog posts. ThePetalGlow only discloses logged in user and commenter IP addresses under the same circumstances that it uses and discloses personally-identifying information as described below.</p>

<h2 id="PII">2. Personally-Identifying Information</h2><p>Certain visitors to ThePetalGlow's websites choose to interact with ThePetalGlow in ways that require ThePetalGlow to gather personally-identifying information. The amount and type of information that ThePetalGlow gathers depends on the nature of the interaction. For example, we ask visitors who leave a comment at https://thepetalglow.com to provide a username and email address.We do not store your credit card information or other sensitive data on our servers.ThePetalGlow uses the services of the most secure payment gateway to provide safe and secure payment procedures. Your credit/debit card information is never transmitted via our website since the payment gateway is responsible for collecting, storing and encrypting your data. All the information that is collected is used for products and services provision, billing, identification and authentication, services improvement, contact and research.
ThePetalGlow does not share your email address or other personally identifying information with any third parties, except our service providers, such as credit-card payment processors, performing services on our behalf. These service providers may have access to personal information needed to perform their functions but are not permitted to share or use such information for any other purposes.</p>

<h2 id="Security">3. Security</h2><p>The security of your Personal Information is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Information, we cannot guarantee its absolute security.We do not sell your Personal Information to anyone for any purpose. We maintain information about you in our business records while you are a customer, or until it is no longer needed for business, tax or legal purposes. We have implemented encryption or other appropriate security controls to protect Personal Information when stored by ThePetalGlow.All the passwords in our web service are hashed by using the Blowfish algorithm brcypt hash function and HMAC SHA256 or RSA algorithm for data tranfer via JWT.Both ThePetalGlow and our third party hosting vendors do the best to protect the personal information from unauthorized access, alteration or disclosure.</p>

<h2 id="ExternalLinks">4. Links To External Sites</h2><p>Our Service may contain links to external sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy and terms of service of every site you visit.</p>
<p>We have no control over, and assume no responsibility for the content, privacy policies or practices of any third party sites, products or services.</p>

<h2 id="PIIProtection">5. Protection of Certain Personally-Identifying Information</h2><p>ThePetalGlow discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on ThePetalGlow's behalf or to provide services available at ThePetalGlow's website, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using ThePetalGlow's website, you consent to the transfer of such information to them. ThePetalGlow will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors and affiliated organizations, as described above, ThePetalGlow discloses potentially personally-identifying and personally-identifying information only in response to a subpoena, court order or other governmental request, or when ThePetalGlow believes in good faith that disclosure is reasonably necessary to protect the property or rights of ThePetalGlow, third parties or the public at large.</p>
<p>If you are a registered user of https://thepetalglow.com and have supplied your email address, ThePetalGlow may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what's going on with ThePetalGlow and our products. We primarily use our blog to communicate this type of information, so we expect to keep this type of email to a minimum. If you send us a request (for example via a support email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. ThePetalGlow takes all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially personally-identifying and personally-identifying information.</p>

<h2 id="Ecommerce">6. E-commerce</h2><p>Those who engage in transactions with ThePetalGlow – by purchasing ThePetalGlow's services or products, are asked to provide additional information, including as necessary the personal and financial information required to process those transactions.In each case, ThePetalGlow collects such information only insofar as is necessary or appropriate to fulfill the purpose of the visitor's interaction with ThePetalGlow. ThePetalGlow does not disclose personally-identifying information as described above other than your registerd username.</p>

<h2 id="businesstransfers">7. Business Transfers</h2><p>If ThePetalGlow, or substantially all of its assets, were acquired, or in the unlikely event that ThePetalGlow goes out of business or enters bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of ThePetalGlow may continue to use your personal information as set forth in this policy.</p>

<h2 id="Changes">8. Privacy Policy Changes</h2><p>Although most changes are likely to be minor, ThePetalGlow may change its Privacy Policy from time to time, and in ThePetalGlow's sole discretion. ThePetalGlow encourages visitors to frequently check this page for any changes to its Privacy Policy. Your continued use of this site after any change in this Privacy Policy will constitute your acceptance of such change.</p>

<h2 id="Credit">9. Contact Information &amp; Credit</h2><p>This privacy policy was created at <a  href="https://privacyterms.io/privacy-policy-generator/" title="Privacy policy generator" target="_blank">privacyterms.io privacy policy generator</a>. If you have any questions about our Privacy Policy, please contact us via <a href="mailto:services@thepetalglow.com">email</a> or <a href="tel:">phone</a>.</p>
        </div>
        </IonContent>
        </IonPage>
        </>
    )
}